services:
  redis:
    image: redis:latest
    container_name: naver-database
    env_file:
      - .env
    ports:
      - '${DB_PORT}:${DB_PORT}'
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - naver-database:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - naver-network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: naver-telemetry
    restart: unless-stopped
    pid: host
    ports:
      - '8080:8080'
    volumes:
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run:/var/run:rw
    networks:
      - naver-network

  server:
    deploy:
      resources:
        limits:
          memory: 2g
        reservations:
          memory: 512m
    container_name: naver-crawler
    build: .
    user: pwuser
    init: true
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    networks:
      - naver-network

networks:
  naver-network:
    name: naver-network

volumes:
  naver-database:
    name: naver-database
